### PR TITLE
Accounts

### PR DESCRIPTION
**Pull request by LukeSwart**
This implements a username to UUID migration for the account key store, along with a script to email users and prompt for a password reset.
**Before merging, I think it would be best to finish issue #47 to reset a password.** There are a couple things not yet implemented for the reset password prompt, like matching a confirmation password in another text box. We may also want to add an option to reset the username as well. 

When testing, be sure to set the env variable `PASSWORD` which is the default password until all users are migrated. (I didn't want to hard code it into our repo!) I also have the server reading `SITE_URL` for the site, since it was defaulting to `http://127.0.0.1:3333`, so you should set `SITE_URL` for production. 

I did some significant refactoring of the account logic as well. It was mostly refactored to better handle reading forms to create/update an account. It might work as an npm module, although it would need more work before doing so.

### CODE REVIEW

**Comment by sethvincent** [comment]
Nice! 

We could just make the username editable on the account edit view.

**Comment by LukeSwart** [comment]
Yes, we can! Although we might not want admins editing other people's usernames, since that affects the login credentials. We can screen it out, so everyone is only able to edit their own username. Let me know if you think otherwise. 

We'll also need to add a uniqueness check to avoid duplicate usernames. Shouldn't be hard, although I wonder if we should just search the entire db or index on usernames as well?

**Comment by sethvincent** [comment]
What do you think about making it so we log in with email instead of username?

Reason: I always forget my usernames.

**Comment by LukeSwart** [comment]
I like that idea. Actually, Github uses two boxes to sign in: `Username or email` and `password`. Either way, we will probably want to change the account-basic login credentials to be `email` and `password`. Should we make it a separate issue, or include it in this PR? It shouldn't be too difficult to include the changes in this migration, although you never know. I can probably have it done over the next week.

Also, I believe we still need to have unique usernames, since that is how users interact with each other on Flatsheet.

**Comment by LukeSwart** [comment]
Recent changes highlights: I added indexes so we can login via username or email, and refactored the accounts logic to create the `forms2accounts` module, although it is not yet published. 

Everything is working, but there are a couple items left:  

 * To correctly make the module uncoupled from our schema, I think we are going to need input validation using a JSON schema (or else a relational database) I don't think it is possible, or a good idea, to have the client perform **all** the validation. In order to prevent the client from storing just about anything on the server without checks, the server will need to perform input validation, probably through a JSON schema and validator. 
 Two examples are the `password` field and `admin` field, where I have hard-coded this validation into our `forms2accounts` server logic. For example, the `password` should not be stored in the account value, so we need a schema of some sort unless we hard-code all passwords to be removed. The `admin` field is also tricky because input checkboxes from html forms don't return a default value if unchecked - they return nothing at all. So we'll need the server to know that an admin field will be present. This is probably best done through a schema validator.
 For next steps on the JSON schema validator, I found an option. [This one](https://github.com/hapijs/joi) looks promising, and I think we discussed [this one](https://github.com/gammasoft/json-validator) although the latter is described as 'not yet ready'.

 * There are a couple features not yet finished - allow changing the username (and finish migrating uuid's instead of usernames in the sheet-owners/sheet-editors store), and matching password confirmation when resetting a password (to prevent typos from permanently changing the password). This should be pretty easy to do. We won't need any of the schema validation stuff to do them.

**Comment by sethvincent** [comment]
one thing that might help is rewriting our forms to have `name` attributes like this:

```html
<form action="/accounts/create" method="post" id="create-account">
    <fieldset>
      <label for="email">email</label>
      <input type="email" name="value[email]">
    </fieldset>
    
    <fieldset>
      <label for="username">username</label>
      <input type="text" name="login[basic][username]">
    </fieldset>
    
    <fieldset>
      <label for="password">password</label>
      <input type="password" name="login[basic][password]">
    </fieldset>
    
    <fieldset>
      <label for="admin">
        <input type="checkbox" name="value[admin]">
        admin
      </label>
    </fieldset>

    <div class="form-actions">
      <input type="submit" value="Create your account">
    </div>
  </form>
</div>
```

Then we get the `{ login: {}, value: {}  }` object like we need when we parse the body.

**Comment by LukeSwart** [comment]
Woohoo! The module is published and manually tested. There are still a few more todo's, but the major issues are finished. Before we can make the migration, I still need to update the migration script to use uuid's instead of usernames.

Here are some remaining items as well. Some are less of a priority:

* TODO display admin status on account listing page
* TODO ensure email and username is unique on new account creation
* TODO add a second password confirmation field when resetting password
* TODO migrate to using uuid's instead of usernames in sheet editors/owners storage
update migration script
* TODO create separate npm module for indexing sheets/accounts

**Comment by LukeSwart** [comment]
I finished the following, most pressing, item:

 - DONE migrate to using uuid's instead of usernames in sheet editors/owners storage update migration script

The other items are less priority and I will make issues for them.

---

I believe this is ready to merge. 

I tested locally with the dev server data, and all is working well. Let me know what you think then we can go ahead an migrate the dev server. If all goes well, let's migrate the production server.

**Comment by sethvincent** [comment]
:tada: :balloon:

**Pull request merged**
